services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:${MONGODB_DATA_PATH}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb

  backend:
    build: ./backend
    ports:
      - "${BACKEND_EXTERNAL_PORT}:5000"
    depends_on:
      - mongodb
    restart: always # this prevents a startup failure (becouse of mongodb not being ready)
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - TEST_USER_EMAIL=${TEST_USER_EMAIL}
      - TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
      

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:5000"
    depends_on:
      - backend
    restart: always # this prevents a startup failure (becouse of backend not being ready)
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000
      - LAST_UPDATE=${LAST_COMMIT}
      - FLASK_DEBUG=1
    volumes:
      - ./frontend:/app

  public-api:
    build: ./public-api
    ports:
      - "${PUBLIC_API_EXTERNAL_PORT}:5000"
    depends_on:
      - backend
    restart: always # this prevents a startup failure (becouse of backend not being ready)
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000 
      - FLASK_DEBUG=1
    volumes:
      - ./public-api:/app


volumes:
  mongo-data:
    driver: local