services:
  mongodb:
    image: mongo:latest
    container_name: ${MONGODB_CONTAINER_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:${MONGODB_DATA_PATH}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}

  backend:
    build: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}
    ports:
      - "88:${BACKEND_FLASK_PORT}"
    depends_on:
      - mongodb
    restart: always # this prevents a startup failure (becouse of mongodb not being ready)
    environment:
      - FLASK_RUN_PORT=${BACKEND_FLASK_PORT}
      - MONGODB_HOST=${MONGODB_CONTAINER_NAME}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      

  frontend:
    build: ./frontend
    container_name: ${FRONTEND_CONTAINER_NAME}
    ports:
      - "80:${FRONTEND_FLASK_PORT}"
    depends_on:
      - backend
    restart: always # this prevents a startup failure (becouse of backend not being ready)
    environment:
      - FLASK_RUN_PORT=${FRONTEND_FLASK_PORT}
      - BACKEND_HOST=${BACKEND_CONTAINER_NAME}
      - BACKEND_PORT=${BACKEND_FLASK_PORT}

  public-api:
    build: ./public-api
    container_name: ${PUBLIC_API_CONTAINER_NAME}
    ports:
      - "8080:${PUBLIC_API_FLASK_PORT}"
    depends_on:
      - backend
    restart: always # this prevents a startup failure (becouse of backend not being ready)
    environment:
      - FLASK_RUN_PORT=${PUBLIC_API_FLASK_PORT}
      - BACKEND_HOST=${BACKEND_CONTAINER_NAME}
      - BACKEND_PORT=${BACKEND_FLASK_PORT}
      - FLASK_DEBUG=1
    volumes:
      - ./public-api:/app

volumes:
  mongo-data:
    driver: local